#FROM node:6.11.1

#WORKDIR /app

#COPY package.json .

#RUN npm install -g npmlog

#RUN npm install -g npm@3.10.9

#RUN npm install

#COPY . .

#RUN npm run build --prod

#CMD [ "npm", "start" ]



FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

#RUN npm install -g npm@3.10.9

RUN npm install

COPY . .

RUN npm run build 

EXPOSE 4200

CMD [ "npm", "start" ]
